image: gitpod/workspace-full-vnc
tasks:
  - before: |
       sdk install java 17.0.6-tem < /dev/null
       ./app_start.sh

ports:
# VNC
  - port: 5900
    onOpen: ignore
# VNC (web view)
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
    - pivotal.vscode-spring-boot
