image: gitpod/workspace-full-vnc
tasks:
  - before: sdk install java 17.0.4.1-tem
  - init: mvn install -DskipTests=false

ports:
# VNC
  - port: 5900
    onOpen: ignore
# VNC (web view)
# This is the port you should be using to interact with Firefox. It is a bit
# annoying to have it open at every workspace startup, though, so it is now
# ignored.
  - port: 6080
    onOpen: ignore
